services:
  base: &default
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/work/
    image: vulkan-rendering:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    shm_size: 48gb
    working_dir: /work/
    user: "1000:1000"

  tty:
    <<: *default
    command: /bin/bash
    tty: true

  sc:
    <<: *default
    command: bash docker/shader_compile.sh

  sc-all:
    <<: *default
    command: bash docker/shader_compile.sh --all
