version: "3.10"

services:
  base: &default
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../:/work/
    image: vulkan-rendering:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    shm_size: 48gb
    working_dir: /work/

  app:
    <<: *default
    command: sleep infinity
